name: CI for React + Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies (Frontend)
        run: npm install
        working-directory: ./frontend

      - name: Run build (Frontend)
        run: npm run build
        working-directory: ./frontend

      - name: Run tests (Frontend)
        run: npm test --if-present
        working-directory: ./frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17 (Spring Boot)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./server

      - name: Run tests (Backend)
        run: mvn test
        working-directory: ./server
